import type { Supplier } from '../types';

const initialSuppliers: Supplier[] = [
  {
    id: '1',
    name: 'XYZ Corporation',
    email: 'contact@xyz.com',
    stage: 'Acquisition',
    stageColor: '#0EA5E9',
    score: 78,
    risk: 'High',
    riskColor: '#F59E0B',
    assessment: 'complete',
    pii: { configured: true, icons: ['ID', 'Email', 'Mobile', 'Doc', 'Location'], method: 'API' },
    piiFlow: 'share',
    contractEnd: 'Mar 2026',
    contractWarning: true,
    agent: 'A1',
    lastActivity: '2 min ago',
    internalSPOC: 'priya@abc.co',
    externalSPOC: 'john@xyz.com',
  },
  {
    id: '2',
    name: 'ABC Services Ltd',
    email: 'ops@abc.com',
    stage: 'Retention',
    stageColor: '#10B981',
    score: 42,
    risk: 'Low',
    riskColor: '#10B981',
    assessment: 'complete',
    pii: { configured: true, icons: ['Email', 'Mobile'], method: 'SFTP' },
    piiFlow: 'ingest',
    contractEnd: 'Dec 2027',
    agent: 'A2',
    lastActivity: '1 hr ago',
    internalSPOC: 'raj@abc.co',
    externalSPOC: 'ops@abcsvc.com',
  },
  {
    id: '3',
    name: 'DEF Limited',
    email: 'info@def.com',
    stage: 'Upgradation',
    stageColor: '#F59E0B',
    score: 62,
    risk: 'Medium',
    riskColor: '#64748B',
    assessment: 'overdue',
    pii: { configured: false },
    piiFlow: 'both',
    contractEnd: 'Jun 2025',
    contractWarning: true,
    agent: 'A3',
    lastActivity: '2 hrs ago',
    internalSPOC: 'anita@abc.co',
    externalSPOC: 'info@def.com',
  },
  {
    id: '4',
    name: 'GHI Technologies',
    email: 'bd@ghi.com',
    stage: 'Acquisition',
    stageColor: '#0EA5E9',
    score: 91,
    risk: 'Critical',
    riskColor: '#EF4444',
    assessment: 'overdue',
    pii: { configured: false },
    piiFlow: 'share',
    contractEnd: 'Sep 2026',
    agent: 'A1',
    lastActivity: '5 hrs ago',
    internalSPOC: 'priya@abc.co',
    externalSPOC: 'bd@ghi.com',
  },
  {
    id: '5',
    name: 'JKL Consultancy',
    email: 'admin@jkl.com',
    stage: 'Retention',
    stageColor: '#10B981',
    score: 35,
    risk: 'Low',
    riskColor: '#10B981',
    assessment: 'complete',
    pii: { configured: true, icons: ['Email'], method: 'Email' },
    piiFlow: 'ingest',
    contractEnd: 'Jan 2028',
    agent: 'A4',
    lastActivity: '3 hrs ago',
    internalSPOC: 'raj@abc.co',
    externalSPOC: 'admin@jkl.com',
  },
  {
    id: '6',
    name: 'MNO Partners',
    email: 'contact@mno.com',
    stage: 'Offboarding',
    stageColor: '#94A3B8',
    score: 55,
    risk: 'Medium',
    riskColor: '#64748B',
    assessment: 'pending',
    pii: { configured: false },
    contractEnd: 'Apr 2026',
    contractWarning: true,
    agent: 'A2',
    lastActivity: '1 day ago',
  },
  {
    id: '7',
    name: 'PQR Systems',
    email: 'info@pqr.com',
    stage: 'Acquisition',
    stageColor: '#0EA5E9',
    score: 67,
    risk: 'Medium',
    riskColor: '#64748B',
    assessment: 'pending',
    pii: { configured: false },
    piiFlow: 'share',
    contractEnd: 'Nov 2027',
    agent: 'A5',
    lastActivity: '6 hrs ago',
  },
  {
    id: '8',
    name: 'STU Analytics',
    email: 'hello@stu.com',
    stage: 'Upgradation',
    stageColor: '#F59E0B',
    score: 22,
    risk: 'Low',
    riskColor: '#10B981',
    assessment: 'complete',
    pii: { configured: false, method: 'configure' },
    piiFlow: 'both',
    contractEnd: 'Jul 2028',
    agent: 'A2',
    lastActivity: '4 hrs ago',
  },
];

export function getSuppliers(): Supplier[] {
  return [...initialSuppliers];
}

export function getSupplierById(id: string): Supplier | undefined {
  return initialSuppliers.find(s => s.id === id);
}
